// This file provides dummy declarations for Deno globals so the standard TypeScript Language Server
// doesn't throw "Cannot find name 'Deno'" errors in the Zed editor.
// It does NOT use wildcard module declarations, so npm packages will resolve naturally via the node_modules folder generated by Deno.

declare namespace Deno {
    export const env: {
        get(key: string): string | undefined;
    };
    export function readTextFile(path: string): Promise<string>;
    export const args: string[];
    export function test(name: string, fn: () => void | Promise<void>): void;
    export function serve(options: any, handler?: any): any;
    export function exit(code?: number): never;
}

declare namespace process {
    export const env: Record<string, string | undefined>;
}

interface ImportMeta {
    main?: boolean;
    url?: string;
    dirname?: string;
}

declare module "@std/assert" {
    export function assertEquals(actual: unknown, expected: unknown, msg?: string): void;
}
