import { dev } from '$app/environment';
import type { Handle } from '@sveltejs/kit';
import { SECURITY_HEADERS, httpsRedirectUrl } from '$lib/server/security-headers';

export const handle: Handle = async ({ event, resolve }) => {
	// Fallback HTTPS redirect — Cloudflare "Always Use HTTPS" is the primary
	// layer; this covers direct HTTP hits for extra safety.
	const location = httpsRedirectUrl(event.request, event.request.headers.get('x-forwarded-proto'));
	if (location) {
		return new Response(null, { status: 301, headers: { Location: location } });
	}

	const response = await resolve(event);

	// Production builds only. The CSP header itself is generated by SvelteKit
	// (kit.csp, mode "hash") — this map carries the rest of the hardening.
	if (!dev) {
		for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
			response.headers.set(name, value);
		}
	}

	return response;
};
